resources:
- name: flight-school
  type: git
  source:
    uri: {{github-url}}
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - put: flight-school
    params: 
      repository: flight-school
      only_tag: true
      tag: ./flight-school/ci/some-tag-file
