resources:
- name: flight-school
  type: git
  source:
    uri: {{github-url}}
    private_key: {{github-private-key}}
    branch: master

jobs:
- name: test-app
  plan:
  - get: flight-school
    trigger: true
  - task: tests
    file: flight-school/build.yml
  - task: bump-ci-check
    file: flight-school/ci/bump-ci-check.yml
  - put: flight-school
    params: 
      repository: updated-repo
      #only_tag: true
      #tag: ./flight-school/ci/some-tag-file
      notes: ./flight-school/ci/git-notes
